[project]
name = "aviation"
version = "0.1.0"
description = "A simple model of global aviation."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
docs = [
    "mkdocs>=1.6.1",
]
